#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_CreatePrediction")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
public partial class msdyn_CreatePredictionRequest : Microsoft.Xrm.Sdk.OrganizationRequest
{
	
	public string ModelState
	{
		get
		{
			if (this.Parameters.Contains("ModelState"))
			{
				return ((string)(this.Parameters["ModelState"]));
			}
			else
			{
				return default(string);
			}
		}
		set
		{
			this.Parameters["ModelState"] = value;
		}
	}
	
	public msdyn_CreatePredictionRequest()
	{
		this.RequestName = "msdyn_CreatePrediction";
	}
}

[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_CreatePrediction")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
public partial class msdyn_CreatePredictionResponse : Microsoft.Xrm.Sdk.OrganizationResponse
{
	
	public msdyn_CreatePredictionResponse()
	{
	}
}
#pragma warning restore CS1591
