#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_InvokeCopilotAPI")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
public partial class msdyn_InvokeCopilotAPIRequest : Microsoft.Xrm.Sdk.OrganizationRequest
{
	
	public string msdyn_APIName
	{
		get
		{
			if (this.Parameters.Contains("msdyn_APIName"))
			{
				return ((string)(this.Parameters["msdyn_APIName"]));
			}
			else
			{
				return default(string);
			}
		}
		set
		{
			this.Parameters["msdyn_APIName"] = value;
		}
	}
	
	public string msdyn_payload
	{
		get
		{
			if (this.Parameters.Contains("msdyn_payload"))
			{
				return ((string)(this.Parameters["msdyn_payload"]));
			}
			else
			{
				return default(string);
			}
		}
		set
		{
			this.Parameters["msdyn_payload"] = value;
		}
	}
	
	public msdyn_InvokeCopilotAPIRequest()
	{
		this.RequestName = "msdyn_InvokeCopilotAPI";
		this.msdyn_APIName = default(string);
		this.msdyn_payload = default(string);
	}
}

[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_InvokeCopilotAPI")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
public partial class msdyn_InvokeCopilotAPIResponse : Microsoft.Xrm.Sdk.OrganizationResponse
{
	
	public msdyn_InvokeCopilotAPIResponse()
	{
	}
	
	public string msdyn_response
	{
		get
		{
			if (this.Results.Contains("msdyn_response"))
			{
				return ((string)(this.Results["msdyn_response"]));
			}
			else
			{
				return default(string);
			}
		}
	}
}
#pragma warning restore CS1591
