#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_PredictResponse")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
public partial class msdyn_PredictResponseRequest : Microsoft.Xrm.Sdk.OrganizationRequest
{
	
	public string version
	{
		get
		{
			if (this.Parameters.Contains("version"))
			{
				return ((string)(this.Parameters["version"]));
			}
			else
			{
				return default(string);
			}
		}
		set
		{
			this.Parameters["version"] = value;
		}
	}
	
	public Microsoft.Xrm.Sdk.Entity requestv2
	{
		get
		{
			if (this.Parameters.Contains("requestv2"))
			{
				return ((Microsoft.Xrm.Sdk.Entity)(this.Parameters["requestv2"]));
			}
			else
			{
				return default(Microsoft.Xrm.Sdk.Entity);
			}
		}
		set
		{
			this.Parameters["requestv2"] = value;
		}
	}
	
	public msdyn_PredictResponseRequest()
	{
		this.RequestName = "msdyn_PredictResponse";
		this.version = default(string);
		this.requestv2 = default(Microsoft.Xrm.Sdk.Entity);
	}
}

[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_PredictResponse")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
public partial class msdyn_PredictResponseResponse : Microsoft.Xrm.Sdk.OrganizationResponse
{
	
	public msdyn_PredictResponseResponse()
	{
	}
	
	public Microsoft.Xrm.Sdk.Entity responsev2
	{
		get
		{
			if (this.Results.Contains("responsev2"))
			{
				return ((Microsoft.Xrm.Sdk.Entity)(this.Results["responsev2"]));
			}
			else
			{
				return default(Microsoft.Xrm.Sdk.Entity);
			}
		}
	}
}
#pragma warning restore CS1591
