#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_ApplyPrediction")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
public partial class msdyn_ApplyPredictionRequest : Microsoft.Xrm.Sdk.OrganizationRequest
{
	
	public string AutoScheduleTrainingConfig
	{
		get
		{
			if (this.Parameters.Contains("AutoScheduleTrainingConfig"))
			{
				return ((string)(this.Parameters["AutoScheduleTrainingConfig"]));
			}
			else
			{
				return default(string);
			}
		}
		set
		{
			this.Parameters["AutoScheduleTrainingConfig"] = value;
		}
	}
	
	public msdyn_ApplyPredictionRequest()
	{
		this.RequestName = "msdyn_ApplyPrediction";
	}
}

[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_ApplyPrediction")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
public partial class msdyn_ApplyPredictionResponse : Microsoft.Xrm.Sdk.OrganizationResponse
{
	
	public msdyn_ApplyPredictionResponse()
	{
	}
}
#pragma warning restore CS1591
