#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_InvokeServiceStoredProc")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
public partial class msdyn_InvokeServiceStoredProcRequest : Microsoft.Xrm.Sdk.OrganizationRequest
{
	
	public int ProcId
	{
		get
		{
			if (this.Parameters.Contains("ProcId"))
			{
				return ((int)(this.Parameters["ProcId"]));
			}
			else
			{
				return default(int);
			}
		}
		set
		{
			this.Parameters["ProcId"] = value;
		}
	}
	
	public int BatchSize
	{
		get
		{
			if (this.Parameters.Contains("BatchSize"))
			{
				return ((int)(this.Parameters["BatchSize"]));
			}
			else
			{
				return default(int);
			}
		}
		set
		{
			this.Parameters["BatchSize"] = value;
		}
	}
	
	public int BatchStart
	{
		get
		{
			if (this.Parameters.Contains("BatchStart"))
			{
				return ((int)(this.Parameters["BatchStart"]));
			}
			else
			{
				return default(int);
			}
		}
		set
		{
			this.Parameters["BatchStart"] = value;
		}
	}
	
	public msdyn_InvokeServiceStoredProcRequest()
	{
		this.RequestName = "msdyn_InvokeServiceStoredProc";
		this.ProcId = default(int);
		this.BatchSize = default(int);
		this.BatchStart = default(int);
	}
}

[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_InvokeServiceStoredProc")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
public partial class msdyn_InvokeServiceStoredProcResponse : Microsoft.Xrm.Sdk.OrganizationResponse
{
	
	public msdyn_InvokeServiceStoredProcResponse()
	{
	}
	
	public string output
	{
		get
		{
			if (this.Results.Contains("output"))
			{
				return ((string)(this.Results["output"]));
			}
			else
			{
				return default(string);
			}
		}
	}
}
#pragma warning restore CS1591
