#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_TrainEffortModel")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
public partial class msdyn_TrainEffortModelRequest : Microsoft.Xrm.Sdk.OrganizationRequest
{
	
	public string TrainConfig
	{
		get
		{
			if (this.Parameters.Contains("TrainConfig"))
			{
				return ((string)(this.Parameters["TrainConfig"]));
			}
			else
			{
				return default(string);
			}
		}
		set
		{
			this.Parameters["TrainConfig"] = value;
		}
	}
	
	public msdyn_TrainEffortModelRequest()
	{
		this.RequestName = "msdyn_TrainEffortModel";
		this.TrainConfig = default(string);
	}
}

[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_TrainEffortModel")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
public partial class msdyn_TrainEffortModelResponse : Microsoft.Xrm.Sdk.OrganizationResponse
{
	
	public msdyn_TrainEffortModelResponse()
	{
	}
	
	public string Result
	{
		get
		{
			if (this.Results.Contains("Result"))
			{
				return ((string)(this.Results["Result"]));
			}
			else
			{
				return default(string);
			}
		}
	}
}
#pragma warning restore CS1591
