#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_TrainAIModel")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
public partial class msdyn_TrainAIModelRequest : Microsoft.Xrm.Sdk.OrganizationRequest
{
	
	public Microsoft.Xrm.Sdk.EntityReference Target
	{
		get
		{
			if (this.Parameters.Contains("Target"))
			{
				return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
			}
			else
			{
				return default(Microsoft.Xrm.Sdk.EntityReference);
			}
		}
		set
		{
			this.Parameters["Target"] = value;
		}
	}
	
	public msdyn_TrainAIModelRequest()
	{
		this.RequestName = "msdyn_TrainAIModel";
		this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
	}
}

[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_TrainAIModel")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
public partial class msdyn_TrainAIModelResponse : Microsoft.Xrm.Sdk.OrganizationResponse
{
	
	public msdyn_TrainAIModelResponse()
	{
	}
	
	public string Response
	{
		get
		{
			if (this.Results.Contains("Response"))
			{
				return ((string)(this.Results["Response"]));
			}
			else
			{
				return default(string);
			}
		}
	}
}
#pragma warning restore CS1591
