#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetGPT3Prediction")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
public partial class msdyn_GetGPT3PredictionRequest : Microsoft.Xrm.Sdk.OrganizationRequest
{
	
	public int msdyn_predictiontype
	{
		get
		{
			if (this.Parameters.Contains("msdyn_predictiontype"))
			{
				return ((int)(this.Parameters["msdyn_predictiontype"]));
			}
			else
			{
				return default(int);
			}
		}
		set
		{
			this.Parameters["msdyn_predictiontype"] = value;
		}
	}
	
	public string msdyn_input
	{
		get
		{
			if (this.Parameters.Contains("msdyn_input"))
			{
				return ((string)(this.Parameters["msdyn_input"]));
			}
			else
			{
				return default(string);
			}
		}
		set
		{
			this.Parameters["msdyn_input"] = value;
		}
	}
	
	public msdyn_GetGPT3PredictionRequest()
	{
		this.RequestName = "msdyn_GetGPT3Prediction";
		this.msdyn_predictiontype = default(int);
		this.msdyn_input = default(string);
	}
}

[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetGPT3Prediction")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
public partial class msdyn_GetGPT3PredictionResponse : Microsoft.Xrm.Sdk.OrganizationResponse
{
	
	public msdyn_GetGPT3PredictionResponse()
	{
	}
	
	public string msdyn_prediction
	{
		get
		{
			if (this.Results.Contains("msdyn_prediction"))
			{
				return ((string)(this.Results["msdyn_prediction"]));
			}
			else
			{
				return default(string);
			}
		}
	}
	
	public int msdyn_status
	{
		get
		{
			if (this.Results.Contains("msdyn_status"))
			{
				return ((int)(this.Results["msdyn_status"]));
			}
			else
			{
				return default(int);
			}
		}
	}
}
#pragma warning restore CS1591
