#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_RetrieveSuggestionPayloads")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
public partial class msdyn_RetrieveSuggestionPayloadsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
{
	
	public Microsoft.Xrm.Sdk.EntityReference SuggestionFor
	{
		get
		{
			if (this.Parameters.Contains("SuggestionFor"))
			{
				return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["SuggestionFor"]));
			}
			else
			{
				return default(Microsoft.Xrm.Sdk.EntityReference);
			}
		}
		set
		{
			this.Parameters["SuggestionFor"] = value;
		}
	}
	
	public string Context
	{
		get
		{
			if (this.Parameters.Contains("Context"))
			{
				return ((string)(this.Parameters["Context"]));
			}
			else
			{
				return default(string);
			}
		}
		set
		{
			this.Parameters["Context"] = value;
		}
	}
	
	public string SuggestionType
	{
		get
		{
			if (this.Parameters.Contains("SuggestionType"))
			{
				return ((string)(this.Parameters["SuggestionType"]));
			}
			else
			{
				return default(string);
			}
		}
		set
		{
			this.Parameters["SuggestionType"] = value;
		}
	}
	
	public string LanguageLocales
	{
		get
		{
			if (this.Parameters.Contains("LanguageLocales"))
			{
				return ((string)(this.Parameters["LanguageLocales"]));
			}
			else
			{
				return default(string);
			}
		}
		set
		{
			this.Parameters["LanguageLocales"] = value;
		}
	}
	
	public msdyn_RetrieveSuggestionPayloadsRequest()
	{
		this.RequestName = "msdyn_RetrieveSuggestionPayloads";
		this.SuggestionFor = default(Microsoft.Xrm.Sdk.EntityReference);
	}
}

[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_RetrieveSuggestionPayloads")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
public partial class msdyn_RetrieveSuggestionPayloadsResponse : Microsoft.Xrm.Sdk.OrganizationResponse
{
	
	public msdyn_RetrieveSuggestionPayloadsResponse()
	{
	}
	
	public Microsoft.Xrm.Sdk.EntityCollection SuggestionPayloads
	{
		get
		{
			if (this.Results.Contains("SuggestionPayloads"))
			{
				return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Results["SuggestionPayloads"]));
			}
			else
			{
				return default(Microsoft.Xrm.Sdk.EntityCollection);
			}
		}
	}
}
#pragma warning restore CS1591
