#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetCopilotSettingsData")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
public partial class msdyn_GetCopilotSettingsDataRequest : Microsoft.Xrm.Sdk.OrganizationRequest
{
	
	public string msdyn_input
	{
		get
		{
			if (this.Parameters.Contains("msdyn_input"))
			{
				return ((string)(this.Parameters["msdyn_input"]));
			}
			else
			{
				return default(string);
			}
		}
		set
		{
			this.Parameters["msdyn_input"] = value;
		}
	}
	
	public msdyn_GetCopilotSettingsDataRequest()
	{
		this.RequestName = "msdyn_GetCopilotSettingsData";
		this.msdyn_input = default(string);
	}
}

[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetCopilotSettingsData")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
public partial class msdyn_GetCopilotSettingsDataResponse : Microsoft.Xrm.Sdk.OrganizationResponse
{
	
	public msdyn_GetCopilotSettingsDataResponse()
	{
	}
	
	public string msdyn_output
	{
		get
		{
			if (this.Results.Contains("msdyn_output"))
			{
				return ((string)(this.Results["msdyn_output"]));
			}
			else
			{
				return default(string);
			}
		}
	}
}
#pragma warning restore CS1591
