#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
public enum msdyn_travelchargetype
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Hourly = 690970000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Mileage = 690970001,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Fixed = 690970002,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	None = 690970003,
}
#pragma warning restore CS1591
