name: Build and test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '15 * * * *'
    
env:
  AZURE_WEBAPP_NAME: AzureFunctionAndApplicationInsights-AusEast    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']
        
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          # Repository name with owner. For example, actions/checkout
          repository: microsoft/PowerApps-TestEngine # optional, default is ${{ github.repository }}
          # The branch, tag or SHA to checkout. When checking out the repository that triggered a workflow, this defaults to the reference or SHA for that event.  Otherwise, uses the default branch.
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          path: tests
          # Repository name with owner. For example, actions/checkout
          #repository: aliyoussefi/TestingPow # optional, default is ${{ github.repository }}
          # The branch, tag or SHA to checkout. When checking out the repository that triggered a workflow, this defaults to the reference or SHA for that event.  Otherwise, uses the default branch.
      - name: Review directory
        run: |
          cd .
          dir
          cd tests
          dir
      - name: Install dependencies
        run: |
          cd src
          dotnet restore
      - name: Build
        run: |
          cd src
          dotnet build --configuration Release --no-restore
      # - name: Test
      #   run: |
      #     cd src
      #     dotnet test --no-restore --verbosity normal --logger:trx --collect:"XPlat Code Coverage" --results-directory ./TestResults
      - name: Integration Test
        env:
            user1Email: '${{ secrets.POWER_PLATFORM_USER }}'
            user1Password: '${{ secrets.POWER_PLATFORM_PASSWORD }}'
        run: |   
          cd src/PowerAppsTestEngine
          dotnet build
          pwsh bin/Debug/net6.0/playwright.ps1 install
          cd ../../build-pipelines/scripts
          chmod +x yaml-integration-tests.sh
          ./yaml-integration-tests.sh "[{ "environmentId": "10195613-f7d0-4d8e-bc74-f8f6bf1fe7d4", "tenantId": "1557f771-4c8e-4dbd-8b80-dd00a88e833e", "domain": "apps.powerapps.com", "testPlanFile": "../../../tests/tests/ayw_canvasappdevelopmentworkshop_1d6fa.fx.yaml", "outputDirectory": "../../TestResults" }]"       # run the script with the parameter, contains logic to run the tests
      - name: Sample Test Report
        uses: dorny/test-reporter@v1.5.0
        if: success() || failure() 
        #if: failure()   # run this step even if previous step failed
        with:
          name: Sample Tests          # Name of the check run which will be created
          path: '**/*.trx'            
          reporter: dotnet-trx        # Format of test results
          fail-on-error: 'true' # Set action as failed if test report contains any failed test      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        if: ${{always()}}
        with:
            name: 'Test Run'
            path: |
                **/TestResults/**
                
     # - name: Azure Login
     #   uses: Azure/login@v1.4.6

     # - name: 'Deploy to Azure WebApp'
     #   id: deploy-to-webapp
     #   uses: azure/webapps-deploy@v2
     #   with:
     #     app-name: ${{ env.AZURE_WEBAPP_NAME }}
     #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
     #     package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
  # yaml-integration-tests-prod:
  #   needs: build
  #   uses: ./.github/workflows/yaml-integration-tests.yml
  #   with: 
  #      parameters: 
  #        '[{ "environmentId": "10195613-f7d0-4d8e-bc74-f8f6bf1fe7d4", "tenantId": "1557f771-4c8e-4dbd-8b80-dd00a88e833e", "domain": "apps.powerapps.com", "testPlanFile": "../../samples/basicgallery/testPlan.fx.yaml", "outputDirectory": "../../TestResults" }]'
  #   secrets: inherit
