# https://github.com/aliyoussefi/EasyRepro
name: TestingEasyReproWithDotNetFramework
# Controls when the workflow will run

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  # This workflow contains a single job called "build"
  Test_EasyRepro_DotNetFramework:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Checkout Easy Repro
        uses: actions/checkout@v4
        with:
          repository: microsoft/EasyRepro
          # ref: develop
          #token: ${{ secrets.AAINTERNAL_READONLY_PAT }} # Access token
          path: easyrepro

      - name: Install dependencies
        run: |
          dir
          cd easyrepro
          dotnet restore

 
